language: go
sudo: false
go:
- 1.11.x
service:
  - redis-server
env:
  matrix:
  - GO111MODULE=on
  global:
    secure: 0NvyN6Ky+A/iMz5S7Y/0K97Iy+Iq0uG24dOj92w6coXuMmlGc5JP7OiEf221tCGYHgttZN5JPrkorw8UflvX1+AJjRjIvyc4ggxuPgs9nmM6Cq5fn2Pato7NvYi1Ly/D1Djse5otmpktOa5DXT/m0e2k18iLiF74jTyIWb+F3t3sqACnwtYbQ32JMVJULYCzj1m2/9rG18a5WduFEKTSqpskpq5oy84NdN2ZApVBDKZCsTOYnDLS/W8cysCZsEcQsVjeKe6knxVXD/kTWisH3mlmxYW3PS5oixrn/EcVmJF97jMsmeuwoa3RIkD8sEl0LypztjBii36ymzsQoEgK+JiT4mpcH84e9z+iofXudYFADIC56TrpFlLxtzP7mjpzI1GH72PxLTFIJDxrIulyYYV94+u0DP23VT9uMsl/Blqjliw6/ex4kuf6JTQy539pTH6sNm3jZyAy/iue/5DTHA0XJOz4aiY6hu8MMOL0VtlDKuNGbVrERxwLhU5wDm2mbfRmeucmWZIgFC47PhOxqrU00YEbXrJk0sMg87ynZYKaBoVgbzUG7po83LrlOGELLpxi534LLxCJQ2HbnYuhXhoWr+6H2O/pd97uyd5XE2F2AmydWMcvJmjnuHKBL9NGKahER+vY1OOyp3K3DHBn+jbP/p6gfwz8caLJ1AdOTKE=
install: true
script:
- go test ./... -coverprofile=coverage.out -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
  sudo service redis-server start --bind 127.0.0.1
notifications:
  slack:
    secure: c+Wufus/yuwKz/LO9Rw/4tR9xOFGRf6rR04E+35cbEIUBMUhV10yvSrLOTUtRL3jIDOUg0IZwy9rhaUWLmIaDQmS9/DMyREsCotbrC/RdFGG57UzzqNlZDZhWEIMCQLKu3Nb9Q5XnhuVIln47RWQVGM/B0X5cd5eVunz96trTEYC/8/MaO0pVtnG9WwNuck6GHPVfQNLvOgyUpVSYlixQmw26YU+18knnZJrx3rQNhax27rcgPdsvj1nVmr0+JnBFZPXjLn6/sj0p5uxuDrEhJ9dGAvzDhpyhxTTkOcwcGVUPDeteCRnfXrsBwAvn5+1cdYRXCLSuC9ECZOYBSMozIhdLz8PWH6+Rpw3BmWXgzuXig8LkdC58B/Iy0NBqrkecoePGvI6Wn9Vx+Exw5Tv1ECyAhVJuu73R437ZON0BHOrTUR+zvhShiiGw7do7cRdUo3rhGavL7U+uAcUg+ZU8XH6K/oAP3UtP0qeNz00ARDg8nHiG4FYMFz3k782WVKf4maz84DpA24/+qT7JMidb4qBJEVkCbOOAfd8hnWL8y2hgyyKpKDwqg/fHiGMQTAANw+RNmFGNJhwCbvvz+pdyeZqTPK+EXWwnH2hSbMbW40HxZWtXNvo1/OnpH3qSHXs7sKNawTX28EMEsh7ydYx4EMbisA1Ud8YByiAbIvwp38=
